# Generated by Django 5.0.2 on 2024-04-28 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='produits',
            new_name='Produits',
        ),
        migrations.AlterField(
            model_name='commande',
            name='dateCde',
            field=models.DateField(default=datetime.date(2024, 4, 28), null=True),
        ),
    ]
