# Generated by Django 4.2.13 on 2024-05-12 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_rename_produits_commande_produits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='dateCde',
            field=models.DateField(default=datetime.date(2024, 5, 12), null=True),
        ),
    ]
